# Analyzer configuration for TCamp Calendar
#
# This file configures the analyzer to enforce modern Dart best practices
# and maintain code quality across the project.

include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    # Treat missing return statements as errors
    missing_return: error
    # Treat unused imports as warnings
    unused_import: warning
    # Treat unused local variables as warnings
    unused_local_variable: warning

linter:
  rules:
    # Style rules
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    
    # Documentation
    public_member_api_docs: false  # Enable later for full documentation
    
    # Code organization
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    directives_ordering: true
    
    # Error prevention
    avoid_print: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    avoid_types_as_parameter_names: true
    avoid_web_libraries_in_flutter: true
    cancel_subscriptions: true
    close_sinks: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    
    # Modern Dart patterns
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_if_null_operators: true
    prefer_null_aware_operators: true
    prefer_spread_collections: true
    prefer_inlined_adds: true
    
    # Type safety
    always_declare_return_types: true
    avoid_dynamic_calls: true
    avoid_init_to_null: true
    
    # Widget best practices
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true
    use_decorated_box: true
    use_colored_box: true
    
    # String handling
    use_string_buffers: true
    prefer_interpolation_to_compose_strings: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    
    # Unnecessary code
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_late: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_checks: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_this: true
    unnecessary_to_list_in_spreads: true

